# Generated by Django 2.2.24 on 2023-08-20 11:10

from django.db import migrations
from django.db.models import When, Case


def fill_new_building_field(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.update(new_building=Case(
        When(construction_year__gte='2015', then=True),
        default=False))


def reset_new_building_field(apps, schema_editor):
    """Set all `new_building` fields to `False`."""
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.update(new_building=None)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(fill_new_building_field,
                             reset_new_building_field),
    ]
